### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by nop33** [muses-fm/muses#96]
Since _Resonate_ is [taken](https://resonate.is/), let's brainstorm in the comments for a new name :) Go wild.

**Comment by OmeGak** [comment]
Once we settle for the new name we need to:
- [x] Rename the GitHub repository
- [x] Move the GitHub repository to a GitHub organization with the same name
- [x] Rename references to `resonate` in the codebase
- [x] Rename the Telegram group name
